### ISSUE TITLE
problem with first run!

### ISSUE THREAD

**Issue by alirezaimi** [davispuh/MySQL-for-Python-3#2]
TypeError: 'use_unicode' is an invalid keyword argument for this function

**Comment by davispuh** [comment]
yes it's correct and expected, because in python 3 all strings are unicode so `mystr = u"unicode string"` is not valid in py3 so in this lib there's no such property as it wouldn't do anything anyway...

to fix your problem if you don't need backward compatibility with py2 just remove it or do something like

```
if sys.version_info[0] <= 2:
    connection.use_unicode = True
```

or if you don't want to change code you can patch it in `MySQLdb/connections.py`

you may want to try [Usage example](https://github.com/davispuh/MySQL-for-Python-3/wiki/Usage%20example) from wiki...

also I suggest to read python 3 documentation about various changes etc...

**Comment by alirezaimi** [comment]
i use this package for connect to mysql from django , But this error happend when i want to run this command :
$python3.2 manage.py sqlall books
TypeError: 'use_unicode' is an invalid keyword argument for this function
how to use your way to solved it ?

Thanks.

**Comment by davispuh** [comment]
I haven't used django, but it's probably not compatible with python 3 so I probably suggest try it with python 2

if you really want to make it working, you'll have to change code in atleast one place, there are 2 ways how to fix it.
this lib for py3 isn't 1:1 when comparing with original for py2, because it takes advantage of py3 and uses "{}" string formating instead of "%s" and also removes "use_unicode" as it's unneeded...

so either you change this lib so it works exactly as for py2 or change code in django

actually I just found there's django for python 3, probably best bet would be trying it: https://github.com/vsajip/django/

also it might be useful contacting django developers about py3 support...

**Comment by katomaso** [comment]
Django has support for python3 since 1.5. (the most recent one). Check if you already has this version (cloning directly from github is the most preferable way).

**Comment by davispuh** [comment]
seems like experimental support and I don't think it's compatible with this lib...

I just looked at source and `use_unicode` is used in [django/db/backends/mysql/base.py#L386](https://github.com/django/django/blob/master/django/db/backends/mysql/base.py#L386) (which shouldn't be there for py3*)

but if looking at that other repository there it's correctly used:
[django/db/backends/mysql/base.py#L387](https://github.com/vsajip/django/blob/django3/django/db/backends/mysql/base.py#L387)

*ok, well if this lib would be 1:1 as for py2 then it would work without any changes :D

**Comment by alirezaimi** [comment]
And What should i do for solve this problem?
Considering the fact that your version of MySQL should support Python3 fully and Django(dev version(1.5)) too.

**Comment by davispuh** [comment]
I already said.... and this MySQL library for python 3 does fully support python 3 (starting from 3.0 till 3.3 and probably next versions if they won't make some big changes...)

BUT even if django does support python 3, then currently it doesn't support this lib... (atleast not django code from master branch nor 1.5 branch), but that other repository maybe does, so another option would be trying merge mysql backend of those 2 repositories...

**Comment by davispuh** [comment]
I'm closing this. It's not issue with this library, it works exactly as it's intended. When I ported this library I didn't had any intentions to make it backward compatible.

Here I've wrote wiki [Differences from MySQL lib for Python 2](https://github.com/davispuh/MySQL-for-Python-3/wiki/Differences-from-MySQL-lib-for-Python-2)
