### ISSUE TITLE
This package does not works with Django

### ISSUE THREAD

**Issue by goinnn** [davispuh/MySQL-for-Python-3#5]
If you change this [function](https://github.com/davispuh/MySQL-for-Python-3/blob/master/MySQLdb/cursors.py#L138) to it, then a Django projects will work:

```
def execute(self, query, args=None):

    ...

    if args is not None:
       query = query % db.literal(args)

    if isinstance(query, str):
        query = query.encode(charset);

    ...
```

You could see an example here:

https://travis-ci.org/goinnn/django-like/builds/15725382#L2000

**Comment by davispuh** [comment]
I've never used Django.

This lib uses Python's 3 new `str..format(...)` and not `%`, it's so because I ported this to py3 very early and then there wasn't `%` in py3, it was added back only later. Also I personally like `.format` better than `%` and this lib was never meant to be backwards compatible, it's py3 only. Thus this is not a bug.

If you need such functionality, then you can use some forks which does implenet it, like [manuelm/MySQL-for-Python-3](/manuelm/MySQL-for-Python-3/commit/2d6b4a91c4dba44dab2ea1d82f132de842d8ffa2)
